# -*- coding: utf-8 -*-
"""Week-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjUU2iHDI0PNzVjJ59MqsvwHrDPiwpev
"""

!pip install faker

import pandas as pd
import numpy as np
import random
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns

fake = Faker()

genders = ["Male", "Female"]
departments = ["CSE", "IT", "ECE"]
years = ["1st", "2nd", "3rd"]

data = []

for i in range(1, 251):
    student = {
        "Student_ID": i,
        "Name": fake.name(),
        "Gender": random.choice(genders),
        "Department": random.choice(departments),
        "Year": random.choice(years),
        "Maths": random.randint(0, 100),
        "Science": random.randint(0, 100),
        "English": random.randint(0, 100),
        "Attendance": random.randint(50, 100),
        "Internal_Marks": random.randint(0, 25)
    }
    data.append(student)

df = pd.DataFrame(data)

df.head()

print("Missing Values:\n", df.isnull().sum())

df = df.drop_duplicates()

print("\nDataset Shape:", df.shape)

df["Total"] = df["Maths"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3

def grade(avg):
    if avg >= 80:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 40:
        return "C"
    else:
        return "Fail"

df["Grade"] = df["Average"].apply(grade)

df.head()

df.describe()

top_students = df.sort_values(by="Average", ascending=False).head(5)
fail_students = df[df["Grade"] == "Fail"]

print("Top 5 Students:\n")
print(top_students)

print("\nFail Students:\n")
print(fail_students)

print("Department-wise Average:\n")
print(df.groupby("Department")["Average"].mean())

print("\nGender-wise Average:\n")
print(df.groupby("Gender")["Average"].mean())

print("\nYear-wise Average:\n")
print(df.groupby("Year")["Average"].mean())

plt.figure()

sns.barplot(
    x="Department",
    y="Average",
    data=df,
    palette="viridis"
)

plt.title("Department-wise Average Performance", weight='bold')
plt.xlabel("Department")
plt.ylabel("Average Marks")

plt.tight_layout()
plt.show()

plt.figure()

df["Gender"].value_counts().plot.pie(
    autopct="%1.1f%%",
    colors=sns.color_palette("pastel"),
    startangle=90,
    wedgeprops={"edgecolor": "black"}
)

plt.title("Gender Distribution", weight='bold')
plt.ylabel("")

plt.tight_layout()
plt.show()

plt.figure()

sns.histplot(df["Average"], bins=12, kde=True, color="skyblue")

plt.axvline(df["Average"].mean(), color='red', linestyle='--', label='Mean')

plt.title("Distribution of Average Marks", weight='bold')
plt.xlabel("Average Marks")
plt.ylabel("Frequency")
plt.legend()

plt.tight_layout()
plt.show()

plt.figure()

sns.scatterplot(
    x="Attendance",
    y="Average",
    data=df,
    hue="Department",
    palette="Set2",
    s=70
)

sns.regplot(
    x="Attendance",
    y="Average",
    data=df,
    scatter=False,
    color="black"
)

plt.title("Attendance vs Performance", weight='bold')
plt.xlabel("Attendance (%)")
plt.ylabel("Average Marks")

plt.tight_layout()
plt.show()

plt.figure()

sns.scatterplot(
    x="Internal_Marks",
    y="Total",
    data=df,
    hue="Year",
    palette="viridis",
    s=70
)

sns.regplot(
    x="Internal_Marks",
    y="Total",
    data=df,
    scatter=False,
    color="black"
)

plt.title("Internal Marks vs Total Marks", weight='bold')
plt.xlabel("Internal Marks")
plt.ylabel("Total Marks")

plt.tight_layout()
plt.show()